plugins:
  discord_bot_enabled:
    default: true
    client: false
  discord_bot_token:
    default: ''
    client: false
  discord_bot_admin_channel_id:
    default: ''
    client: false
  discord_bot_admin_role_id:
    default: ''
    client: false
  discord_bot_announcement_channel_id:
    default: ''
    client: false
  discord_bot_discourse_announcement_topic_id:
    default: ''
    client: false
  discord_bot_post_announcement_categories:
    client: false
    default: ''
    type: category_list
  discord_bot_topic_announcement_categories:
    client: false
    default: ''
    type: category_list
  discord_bot_topic_announcement_delay_seconds:
    default: 5
    client: false
  discord_bot_auto_channel_sync:
    default: false
    client: false
  discord_bot_message_copy_topic_size_limit:
    default: 100
    client: false
  discord_bot_message_copy_default_category:
    client: false
    default: ''
    type: category_list
  discord_bot_message_copy_convert_discord_mentions_to_usernames:
    client: false
    default: true
  discord_bot_message_copy_ignore_bot_messages:
    client: false
    default: true
  discord_bot_unknown_user_proxy_account:
    client: false
    type: username
    default: system
  discord_bot_rate_limit_delay:
    default: 2
    client: false
